### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by not-matthias** [dephraiim/minimal-youtube#3]
Neat project, is a firefox version of this also planned?

**Comment by Shiqan** [comment]
In the manifest.json, you need to set the version to `2`, 3 is not supported yet by Firefox ([it is in preview](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/)).
And then I had to change 2 small things in the content.js file to get it to work:
1. remove `window.onload = function () {` (and the corresponding closing bracket)
1. replace `const replaceHomePage = () => {` with `function replaceHomePage() {` 

Not sure why though since both are basic JS functionality supposedly supported by Firefox 🤷‍♂️

**Comment by pylipp** [comment]
@Shiqan can you describe how to integrate the extension in Firefox then? I downloaded the zip, extracted and modified the files as per your suggestion, and zipped it up again.
When loading it from `about:addons` I still get the message "could not be loaded, appears to be corrupt". Using FF105.

Below the diff:
```diff
diff --git a/content.js b/content.js
index af2f2bc..aa8bc60 100644
--- a/content.js
+++ b/content.js
@@ -1,7 +1,6 @@
 /* This runs after a web page loads */
 var oldHref = document.location.href;
 
-window.onload = function () {
   var bodyList = document.querySelector("body");
 
   var observer = new MutationObserver(function (mutations) {
@@ -20,9 +19,8 @@ window.onload = function () {
 
   observer.observe(bodyList, config);
   replaceHomePage();
-};
 
-const replaceHomePage = () => {
+function replaceHomePage() {
   document.querySelector("body").style.cssText = "display:block !important";
   if (window.location.pathname === "/") {
     document.querySelector("body").innerHTML = `
diff --git a/manifest.json b/manifest.json
index 29f6e41..4c16503 100644
--- a/manifest.json
+++ b/manifest.json
@@ -1,5 +1,5 @@
 {
-  "manifest_version": 3,
+  "manifest_version": 2,
 
   "name": "Minimal YouTube",
   "version": "0.1.0",
```

**Comment by dephraiim** [comment]
I use the `web-ext` CLI tool and it works by packaging it and opening it in Firefox.
